import { useState, useEffect } from 'react';
import { getNotifications, createNotification, deleteNotification } from '../api';

function Notifications() {
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(null);
  const [formData, setFormData] = useState({ userId: '', message: '', type: 'info' });

  const fetchNotifications = async () => {
    try {
      setLoading(true);
      const response = await getNotifications();
      // API returns array directly, not wrapped in object
      const notificationsData = Array.isArray(response.data) ? response.data : [];
      setNotifications(notificationsData);
      setError(null);
    } catch (err) {
      setError('Failed to fetch notifications: ' + err.message);
      console.error('Fetch notifications error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchNotifications();
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await createNotification(formData);
      setSuccess('Notification created successfully!');
      setFormData({ userId: '', message: '', type: 'info' });
      fetchNotifications();
      setTimeout(() => setSuccess(null), 3000);
    } catch (err) {
      setError('Creation failed: ' + err.message);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this notification?')) {
      try {
        await deleteNotification(id);
        setSuccess('Notification deleted successfully!');
        fetchNotifications();
        setTimeout(() => setSuccess(null), 3000);
      } catch (err) {
        setError('Delete failed: ' + err.message);
      }
    }
  };

  const getTypeColor = (type) => {
    switch (type) {
      case 'success': return '#10b981';
      case 'error': return '#ef4444';
      case 'warning': return '#f59e0b';
      default: return '#3b82f6';
    }
  };

  return (
    <div className="main-content">
      <div className="top-bar">
        <h2 className="page-title">System Notifications</h2>
        <button onClick={fetchNotifications} className="btn-icon">
          🔄
        </button>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
        <div className="form-panel" style={{ width: '100%' }}>
          <h3 style={{ marginBottom: '24px', color: 'white' }}>Send Notification</h3>

          {error && <div className="status-badge status-unhealthy" style={{ marginBottom: '16px', width: '100%' }}>{error}</div>}
          {success && <div className="status-badge status-healthy" style={{ marginBottom: '16px', width: '100%' }}>{success}</div>}

          <div className="status-badge status-healthy" style={{ marginBottom: '24px', width: '100%', display: 'block', lineHeight: '1.5', background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.2)' }}>
            <strong>Note:</strong> Most notifications are auto-generated by the Order Service.
          </div>

          <form onSubmit={handleSubmit}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '24px' }}>
              <div className="form-group">
                <label>User ID</label>
                <input
                  type="text"
                  value={formData.userId}
                  onChange={(e) => setFormData({ ...formData, userId: e.target.value })}
                  required
                  placeholder="Enter user ID"
                />
              </div>
              <div className="form-group">
                <label>Message</label>
                <input
                  type="text"
                  value={formData.message}
                  onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                  required
                  placeholder="Enter notification message"
                />
              </div>
              <div className="form-group">
                <label>Type</label>
                <select
                  value={formData.type}
                  onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                >
                  <option value="info">Info</option>
                  <option value="success">Success</option>
                  <option value="warning">Warning</option>
                  <option value="error">Error</option>
                </select>
              </div>
            </div>
            <button type="submit" className="btn btn-primary" style={{ width: '100%', marginTop: '24px' }}>
              Send Notification
            </button>
          </form>
        </div>

        <div className="panel" style={{ padding: '0', overflow: 'hidden', width: '100%' }}>
          <div className="panel-header" style={{ padding: '24px', borderBottom: '1px solid var(--border-glass)' }}>
            <h3 style={{ margin: 0 }}>Notification Log ({notifications.length})</h3>
          </div>

          {loading ? (
            <div className="loading" style={{ padding: '40px', textAlign: 'center', color: 'var(--text-secondary)' }}>Loading notifications...</div>
          ) : notifications.length === 0 ? (
            <div className="loading" style={{ padding: '40px', textAlign: 'center', color: 'var(--text-secondary)' }}>No notifications found.</div>
          ) : (
            <div className="table-container">
              <table style={{ width: '100%' }}>
                <thead>
                  <tr>
                    <th style={{ width: '10%' }}>ID</th>
                    <th style={{ width: '40%' }}>Message</th>
                    <th style={{ width: '15%' }}>Type</th>
                    <th style={{ width: '15%' }}>User</th>
                    <th style={{ textAlign: 'right', width: '20%' }}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {notifications.map((notification) => (
                    <tr key={notification.id}>
                      <td style={{ fontFamily: 'monospace', color: 'var(--primary)' }}>#{notification.id}</td>
                      <td>
                        <div style={{ fontWeight: '500', color: 'white' }}>{notification.message}</div>
                        <div style={{ fontSize: '12px', color: 'var(--text-secondary)', marginTop: '4px' }}>
                          {notification.timestamp ? new Date(notification.timestamp).toLocaleString() : 'Just now'}
                        </div>
                      </td>
                      <td>
                        <span 
                          className="status-badge"
                          style={{ 
                            background: `${getTypeColor(notification.type)}20`,
                            color: getTypeColor(notification.type),
                            border: `1px solid ${getTypeColor(notification.type)}40`
                          }}
                        >
                          {notification.type}
                        </span>
                      </td>
                      <td>User #{notification.userId}</td>
                      <td style={{ textAlign: 'right' }}>
                        <button
                          onClick={() => handleDelete(notification.id)}
                          className="btn btn-danger"
                          style={{ padding: '8px 16px', fontSize: '12px' }}
                        >
                          Delete
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default Notifications;
